// Month narrative — the ledger, in sentences.
//
// Generated by rules over figures the app already computes, never by guesswork.
// The governing constraint: say the two or three things that are unusual about
// this month, or say nothing. A paragraph that appears every month regardless of
// content reads as filler and trains you to skip it.
import type { EnrichedSession, MonthSummary } from './savings'
import { aud, kwh, rate } from './format'

export interface NarrativeSeg {
  text: string
  /** Rendered emphasised; the month total is also long-pressable. */
  em?: boolean
  /** Marks the month total so the view can attach its derivation. */
  total?: boolean
}

export interface MonthNarrative {
  /** Always present: what the month cost and what it bought. */
  opening: NarrativeSeg[]
  /** Nothing-to-see months return an empty list rather than padding. */
  points: NarrativeSeg[][]
  /** Set when the month is still running. */
  partial?: string
}

const seg = (text: string): NarrativeSeg => ({ text })
const em = (text: string): NarrativeSeg => ({ text, em: true })

const dayOrdinal = (iso: string) => {
  const n = Number(iso.slice(8, 10))
  const suffix = n % 10 === 1 && n !== 11 ? 'st' : n % 10 === 2 && n !== 12 ? 'nd' : n % 10 === 3 && n !== 13 ? 'rd' : 'th'
  return `${n}${suffix}`
}

/**
 * Build the narrative for one month.
 * `prev` is the preceding month if it exists; `daysElapsed`/`daysInMonth` drive
 * the partial-month note.
 */
export function narrateMonth(
  m: MonthSummary,
  sessions: EnrichedSession[],
  prev: MonthSummary | undefined,
  daysElapsed: number,
  daysInMonth: number,
): MonthNarrative | null {
  if (!m || m.sessions === 0) return null

  const energyCost = m.cost - m.fees
  const charges = sessions.filter(s => !s.isFee)
  const net = m.saved - m.fees
  const partial = daysElapsed < daysInMonth

  // ---- opening: what it cost, and what it bought ----
  const opening: NarrativeSeg[] = [seg('You spent ')]
  opening.push({ text: aud(m.cost), em: true, total: true })
  if (m.fees > 0) {
    opening.push(
      seg(' — '),
      em(aud(m.fees)),
      seg(' of membership and '),
      em(aud(energyCost)),
      seg(` of electricity across ${charges.length} charge${charges.length === 1 ? '' : 's'}.`),
    )
  } else {
    opening.push(seg(` across ${charges.length} charge${charges.length === 1 ? '' : 's'}.`))
  }

  if (m.freeKwh > 0) {
    opening.push(
      seg(' You claimed '),
      em(`${kwh(m.freeKwh, 1)} kWh`),
      seg(' of free energy, worth '),
      em(aud(m.saved)),
      m.fees > 0
        ? net >= 0
          ? seg(', so you are ')
          : seg(', which left you ')
        : seg('.'),
    )
    if (m.fees > 0) {
      opening.push(em(aud(Math.abs(net))), seg(net >= 0 ? ' ahead on the month.' : ' behind on the month.'))
    }
  }

  // ---- points: only what stands out ----
  const points: NarrativeSeg[][] = []

  // A single charge dominating the energy bill.
  if (energyCost > 0.5 && charges.length > 1) {
    const dearest = charges.reduce((a, s) => (s.cost > a.cost ? s : a), charges[0])
    const share = dearest.cost / energyCost
    if (share >= 0.4) {
      const line: NarrativeSeg[] = [
        seg('Almost all of that electricity came from '),
        em(`one charge on the ${dayOrdinal(dearest.date)}`),
        seg(', where '),
      ]
      if (dearest.paidKwh > 0 && dearest.freeKwh > 0) {
        line.push(
          em(`${dearest.paidKwh.toFixed(1)} kWh`),
          seg(' went past the daily allowance at '),
          em(`${rate(dearest.billedRate)}/kWh`),
          seg('.'),
        )
      } else {
        line.push(em(`${dearest.amount.toFixed(1)} kWh`), seg(' cost '), em(aud(dearest.cost)), seg('.'))
      }
      points.push(line)
    }
  }

  // A month with no paid energy at all is worth saying out loud.
  if (energyCost === 0 && m.kwh > 0) {
    points.push([seg('Every kWh this month was free — you paid nothing for electricity.')])
  }

  // Month-on-month movement, but only when it is material and comparable.
  if (prev && !partial && prev.cost > 0) {
    const delta = m.cost - prev.cost
    const pct = Math.abs(delta / prev.cost) * 100
    if (pct >= 15) {
      points.push([
        seg(`That is `),
        em(aud(Math.abs(delta))),
        seg(` ${delta > 0 ? 'more' : 'less'} than ${prev.label.split(' ')[0]}, ${pct.toFixed(0)}% ${delta > 0 ? 'up' : 'down'}.`),
      ])
    }
  }

  return {
    opening,
    points: points.slice(0, 2),
    partial: partial ? `${daysElapsed} of ${daysInMonth} days elapsed — the month is still running.` : undefined,
  }
}
